main: de.timesnake.extension.bukkit.main.ExBukkit
version: 1.3.2
name: extension-bukkit
author: timesnake
depend: [ basic-bukkit ]
api-version: 1.13

commands:
  teleport:
    aliases: [ tp ]
  teleporthere:
    aliases: [ tph, tphere ]
  teleportask:
    aliases: [ tpa, teleporta, tpask, call ]
  teleportaskhere:
    aliases: [ tpahere, tpaskhere, tpaskh, tpah ]
  tpback:
  tpaccept:
  tpdeny:
  tpatoggle:

  tphall:
    aliases: [ tphereall ]

  spawn:
  setspawn:

  time:
  day:
  night:
  noon:

  gamemode:
    aliases: [ gm, gmode ]

  weather:
  sun:
  rain:
  thunder:
  storm:
  speed:
  speedfly:
  speedwalk:

  inventory:
    aliases: [ inv, invsee ]
  invclear:
    aliases: [ clear ]

  fly:

  vanish:
    aliases: [ v ]

  god:

  afk:
    aliases: [ awayfromkeyboard ]
  afktoggle:

  kill:
  killall:

  heal:

  mw:
    aliases: [ multiw, multiworlds, multiworld ]

  chatcopy:
    aliases: [ cc, ccopy ]

  nightvision:
    aliases:
      - nivi
     